ARCHS = arm64 arm64e

export SDKVERSION = 13.4

INSTALL_TARGET_PROCESSES = SpringBoard

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = NoMoreScrollstoTop

NoMoreScrollstoTop_FILES = NoMoreScrollstoTop.xm
NoMoreScrollstoTop_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
