ARCHS = arm64 arm64e

SDKVERSION = 13.5

INSTALL_TARGET_PROCESSES = SpringBoard

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = Haptic

Haptic_FILES = Haptic.xm
Haptic_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
